const data = [
  // Wed Sep 9
  { time: "00:40", outcome: "LOSS" },
  { time: "01:20", outcome: "WIN" },
  { time: "04:07", outcome: "LOSS" },
  { time: "04:40", outcome: "WIN" },
  { time: "08:10", outcome: "LOSS" },
  { time: "10:55", outcome: "LOSS" },
  { time: "11:10", outcome: "WIN" },
  { time: "12:10", outcome: "WIN" },
  { time: "12:30", outcome: "LOSS" },
  { time: "13:50", outcome: "LOSS" },
  { time: "15:15", outcome: "LOSS" },
  { time: "16:05", outcome: "WIN" },
  { time: "16:20", outcome: "WIN" },
  { time: "17:10", outcome: "WIN" },
  { time: "17:35", outcome: "WIN" },
  { time: "18:23", outcome: "WIN" },
  { time: "18:48", outcome: "WIN" },
  { time: "21:35", outcome: "WIN" },
  { time: "21:45", outcome: "WIN" },
  { time: "22:15", outcome: "WIN" },

  // Thu Sep 10
  { time: "00:50", outcome: "WIN" },
  { time: "00:57", outcome: "WIN" },
  { time: "01:20", outcome: "WIN" },
  { time: "02:15", outcome: "LOSS" },
  { time: "03:15", outcome: "WIN" },
  { time: "03:45", outcome: "WIN" },
  { time: "04:30", outcome: "LOSS" },
  { time: "05:20", outcome: "LOSS" },
  { time: "06:45", outcome: "WIN" },
  { time: "07:00", outcome: "WIN" },
  { time: "07:40", outcome: "WIN" },
  { time: "08:50", outcome: "LOSS" },
  { time: "09:50", outcome: "WIN" },
  { time: "10:20", outcome: "WIN" },
  { time: "10:35", outcome: "WIN" },
  { time: "11:25", outcome: "WIN" },
  { time: "11:34", outcome: "WIN" },
  { time: "12:00", outcome: "WIN" },
  { time: "12:15", outcome: "LOSS" },
  { time: "12:40", outcome: "WIN" },
  { time: "13:00", outcome: "LOSS" },
  { time: "13:30", outcome: "WIN" },
  { time: "14:10", outcome: "WIN" },
  { time: "14:35", outcome: "LOSS" },
  { time: "15:00", outcome: "LOSS" },
  { time: "15:20", outcome: "WIN" },
  { time: "16:14", outcome: "WIN" },
  { time: "16:45", outcome: "WIN" },
  { time: "17:05", outcome: "LOSS" },
  { time: "17:30", outcome: "WIN" },
  { time: "18:30", outcome: "LOSS" },
  { time: "19:45", outcome: "WIN" },
  { time: "21:45", outcome: "WIN" },
  { time: "22:10", outcome: "LOSS" },
  { time: "22:25", outcome: "WIN" },
  { time: "22:50", outcome: "WIN" },

  // Fri Sep 11
  { time: "00:00", outcome: "WIN" },
  { time: "00:10", outcome: "LOSS" },
  { time: "00:40", outcome: "WIN" },
  { time: "01:25", outcome: "LOSS" },
  { time: "01:35", outcome: "WIN" },
  { time: "03:25", outcome: "WIN" },
  { time: "03:35", outcome: "WIN" },
  { time: "03:45", outcome: "WIN" },
  { time: "05:10", outcome: "WIN" },
  { time: "05:45", outcome: "LOSS" },
  { time: "06:30", outcome: "WIN" },
  { time: "06:30", outcome: "WIN" },
  { time: "06:46", outcome: "LOSS" },
  { time: "07:35", outcome: "WIN" },
  { time: "08:00", outcome: "WIN" },
  { time: "08:45", outcome: "LOSS" },
  { time: "09:45", outcome: "LOSS" },
  { time: "09:46", outcome: "WIN" },
  { time: "10:35", outcome: "LOSS" },
  { time: "11:15", outcome: "LOSS" },
  { time: "11:46", outcome: "WIN" },
  { time: "12:00", outcome: "WIN" },
  { time: "12:10", outcome: "WIN" },
  { time: "12:40", outcome: "WIN" },
  { time: "13:05", outcome: "WIN" },
  { time: "13:05", outcome: "LOSS" },
  { time: "14:20", outcome: "LOSS" },
  { time: "14:55", outcome: "LOSS" },
  { time: "16:15", outcome: "WIN" },
  { time: "17:25", outcome: "WIN" },
  { time: "19:25", outcome: "WIN" },
  { time: "19:50", outcome: "WIN" },
  { time: "20:15", outcome: "WIN" },
  { time: "20:50", outcome: "LOSS" },
  { time: "22:05", outcome: "WIN" },

  // Sat Sep 12
  { time: "00:30", outcome: "WIN" },
  { time: "01:25", outcome: "WIN" },
  { time: "01:25", outcome: "LOSS" },
  { time: "02:10", outcome: "LOSS" },
  { time: "02:20", outcome: "WIN" },
  { time: "02:30", outcome: "WIN" },
  { time: "02:35", outcome: "WIN" },
  { time: "03:45", outcome: "LOSS" },
  { time: "04:35", outcome: "LOSS" },
  { time: "05:20", outcome: "WIN" },
  { time: "05:25", outcome: "LOSS" },
  { time: "05:30", outcome: "LOSS" },
  { time: "05:35", outcome: "WIN" },
  { time: "06:05", outcome: "WIN" },
  { time: "06:50", outcome: "WIN" },
  { time: "07:50", outcome: "LOSS" },
  { time: "08:51", outcome: "LOSS" },
  { time: "09:05", outcome: "LOSS" },
  { time: "09:08", outcome: "WIN" },
  { time: "09:15", outcome: "WIN" },
  { time: "10:20", outcome: "WIN" },
  { time: "10:50", outcome: "WIN" },
  { time: "11:35", outcome: "WIN" },
  { time: "12:10", outcome: "WIN" },
  { time: "12:33", outcome: "WIN" },
  { time: "14:10", outcome: "WIN" },
  { time: "14:25", outcome: "LOSS" },
  { time: "15:10", outcome: "WIN" },
  { time: "15:55", outcome: "WIN" },
  { time: "16:40", outcome: "WIN" },
  { time: "18:40", outcome: "WIN" },
  { time: "19:15", outcome: "LOSS" },
  { time: "20:55", outcome: "LOSS" },
  { time: "21:20", outcome: "LOSS" },
  { time: "22:30", outcome: "LOSS" },

  // Sun Sep 13
  { time: "00:00", outcome: "LOSS" },
  { time: "00:00", outcome: "LOSS" },
  { time: "00:45", outcome: "LOSS" },
  { time: "01:31", outcome: "WIN" },
  { time: "01:43", outcome: "WIN" },
  { time: "01:45", outcome: "LOSS" },
  { time: "02:40", outcome: "LOSS" },
  { time: "02:50", outcome: "LOSS" },
  { time: "04:00", outcome: "LOSS" },
  { time: "04:15", outcome: "WIN" },
  { time: "05:20", outcome: "WIN" },
  { time: "06:05", outcome: "LOSS" },
  { time: "06:45", outcome: "LOSS" },
  { time: "07:10", outcome: "WIN" },
  { time: "10:36", outcome: "WIN" },
  { time: "11:30", outcome: "WIN" },
  { time: "11:45", outcome: "LOSS" },
  { time: "11:50", outcome: "LOSS" },
  { time: "14:15", outcome: "LOSS" },
  { time: "14:20", outcome: "LOSS" },
  { time: "14:30", outcome: "LOSS" },
  { time: "15:15", outcome: "WIN" },
  { time: "15:42", outcome: "WIN" },
  { time: "16:05", outcome: "WIN" },
  { time: "17:12", outcome: "WIN" },
  { time: "18:00", outcome: "LOSS" },
  { time: "18:15", outcome: "WIN" },
  { time: "18:35", outcome: "WIN" },
  { time: "21:30", outcome: "LOSS" },
  { time: "22:30", outcome: "WIN" },

  // Mon Sep 14
  { time: "00:05", outcome: "WIN" },
  { time: "00:15", outcome: "LOSS" },
  { time: "00:45", outcome: "LOSS" },
  { time: "01:05", outcome: "LOSS" },
  { time: "01:44", outcome: "WIN" },
  { time: "02:35", outcome: "LOSS" },
  { time: "02:56", outcome: "LOSS" },
  { time: "03:00", outcome: "WIN" },
  { time: "03:35", outcome: "LOSS" },
  { time: "03:40", outcome: "LOSS" },
  { time: "04:55", outcome: "WIN" },
  { time: "04:57", outcome: "LOSS" },
  { time: "07:00", outcome: "WIN" },
  { time: "08:30", outcome: "LOSS" },
  { time: "09:35", outcome: "LOSS" },
  { time: "10:00", outcome: "LOSS" },
  { time: "10:50", outcome: "WIN" },
  { time: "12:55", outcome: "WIN" },
  { time: "13:06", outcome: "WIN" },
  { time: "13:15", outcome: "WIN" },
  { time: "13:55", outcome: "WIN" },
  { time: "14:48", outcome: "WIN" },
  { time: "15:20", outcome: "LOSS" },
  { time: "16:00", outcome: "WIN" },
  { time: "17:25", outcome: "WIN" },
  { time: "17:50", outcome: "LOSS" },
  { time: "18:55", outcome: "WIN" },

  // Tue Sep 15
  { time: "00:15", outcome: "LOSS" },
  { time: "00:25", outcome: "LOSS" },
  { time: "00:55", outcome: "LOSS" },
  { time: "03:50", outcome: "LOSS" },
  { time: "03:50", outcome: "WIN" },
  { time: "04:55", outcome: "LOSS" },
  { time: "05:55", outcome: "WIN" },
  { time: "06:50", outcome: "LOSS" },
  { time: "08:40", outcome: "LOSS" },
  { time: "09:00", outcome: "LOSS" },
  { time: "11:40", outcome: "LOSS" },
  { time: "13:25", outcome: "WIN" },
  { time: "18:05", outcome: "LOSS" },
  { time: "19:14", outcome: "WIN" },
  { time: "21:50", outcome: "WIN" },
];

let earlyWins = 0, earlyLosses = 0;
let restWins = 0, restLosses = 0;

data.forEach(d => {
  const hour = parseInt(d.time.split(':')[0], 10);
  if (hour < 8) {
    if (d.outcome === 'WIN') earlyWins++;
    else earlyLosses++;
  } else {
    if (d.outcome === 'WIN') restWins++;
    else restLosses++;
  }
});

console.log(`--- EARLY HOURS (00:00 - 08:00 UTC) ---`);
console.log(`Trades: ${earlyWins + earlyLosses} | Wins: ${earlyWins} | Losses: ${earlyLosses} | Win Rate: ${(earlyWins/(earlyWins+earlyLosses)*100).toFixed(1)}%`);
const earlyNetR = (earlyWins * 1.3) - earlyLosses;
console.log(`Net R in Early Hours: ${earlyNetR.toFixed(1)} R`);

console.log(`\n--- REST OF DAY (08:00 - 24:00 UTC) ---`);
console.log(`Trades: ${restWins + restLosses} | Wins: ${restWins} | Losses: ${restLosses} | Win Rate: ${(restWins/(restWins+restLosses)*100).toFixed(1)}%`);
const restNetR = (restWins * 1.3) - restLosses;
console.log(`Net R in Rest of Day: ${restNetR.toFixed(1)} R`);
